# SELECT DECODING TARGET
# --------------------------------------------------
# single-bin targets
# - pLeft
# - signcont
# - choice
# - feedback
#
# multi-bin targets
# - wheel-vel
# - wheel-speed
# - pupil
# - l-paw-pos
# - l-paw-vel
# - l-paw-speed
# - l-whisker-me
# - r-paw-pos
# - r-paw-vel
# - r-paw-speed
# - r-whisker-me
target: pLeft

# model of prior
# - expSmoothing_prevAction
# - optimal_Bayesian
# - oracle (experimenter-defined 0.2/0.8)
model: oracle


# TIME WINDOW PARAMS
# --------------------------------------------------
# event on which windows are aligned
# - firstMovement_times
# - goCue_times
# - stimOn_times
# - feedback_times
align_time: goCue_times

# start and end of decoding window, relative to align_time (seconds)
time_window: [-0.25, 1.0]

# size of individual bins within time window (seconds)
binsize: 0.02

# number of bins to use for prediction
n_bins_lag: 10


# DECODER PARAMS
# --------------------------------------------------
# sklearn model
# - linear
# - lasso (linear + L1)
# - ridge (linear + L2)
# - logistic
estimator: ridge

# default args for decoder
estimator_kwargs:
    tol: 0.0001
    max_iter: 10000
    fit_intercept: true

# hyperparameter values to search over
hyperparam_grid:
    alpha: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0, 10]
    C: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0, 10]

# number of pseudo/imposter sessions to fit
n_pseudo: 2

# number of pseudo/imposter sessions to assign per cluster job
n_pseudo_per_job: 50

# number of times to repeat full nested xv with different folds
n_runs: 5

# true for interleaved xv, false for contiguous
shuffle: true

# normalization
normalize_input: false
normalize_output: false

balanced_weight: false
balanced_continuous_target: false


# CLUSTER/UNIT PARAMS
# --------------------------------------------------
# type of neural data
# - ephys
# - widefield
neural_dtype: ephys

# regions with units below this threshold are skipped
min_units: 10

# fraction of qc criteria each unit needs to pass for inclusion
qc_criteria: 1.0

# perform decoding on region-wise or whole-brain decoding
single_region: true

# merge probes before performing analysis
merge_probes: false


# SESSION/BEHAVIOR PARAMS
# --------------------------------------------------
# aligned -> histology was performed by one experimenter
# resolved -> histology was performed by 2-3 experimenters
criterion: aligned-behavior

# minimum number of behavioral trials completed by subject
min_behav_trials: 300

# remove trials with reaction times below/above these values (seconds)
min_rt: 0.08
max_rt: null

# min length of trials (seconds) (can be null)
min_len: 1.0

# max length of trials (seconds) (can be null)
max_len: 5.0

# true to take out unbiased block at beginning of session
no_unbias: false

# number of trials to remove from the end of the session (why?)
nb_trials_takeout_end: 0


# NULL DISTRIBUTION PARAMS
# --------------------------------------------------
# false will use pseudo-sessions to create null distributions
use_imposter_session: false

# true to just use ephys sessions, false to use training sessions (more templates)
imposter_generate_from_ephys: true

# TODO
constrain_imposter_session_with_beh: false

# TODO
stitching_for_imposter_session: false

# if false, simulate the model (should be false)
use_imposter_session_for_balancing: false

# testing purposes?
imposter_generate_fake: false


# MISC PARAMS
# --------------------------------------------------
# date as a string, or null to replace with today's date
date: '2022-06-03'

simulate_neural_data: false

# uses openturns to perform kernel density estimation
use_openturns: false
bin_size_kde: 0.02

save_predictions: true
save_predictions_pseudo: false
save_binned: false

# if true, trains the behavioral model session-wise else mouse-wise
beh_mouseLevel_training: false

# to binarize the target -> could be useful with logistic regression estimator
binarization_value: null

# TODO
compute_on_each_fold: true

# control random seeds while fitting
quasi_random: true


# NEUROMETRIC PARAMS
# --------------------------------------------------
compute_neurometric: false

border_quantiles_neurometric: []  # [0.3, 0.7]

force_positive_neuro_slopes: false


# WIDEFIELD PARAMS
# --------------------------------------------------
widefield: false

# 'left' and/or 'right'
widefield_hemispheres: ['left']

# signed number of frames from align time
widefield_nb_frames: -1