name: iblenv
dependencies:
  - python=3.9
  - apptools >= 4.5.0
  - boto3
  - click
  - colorcet
  - colorlog
  - cython
  - dataclasses
  - flake8
  - graphviz
  - h5py
  - ipython
  - matplotlib
  - numba
  - numpy
  - pandas
  - plotly
  - pyarrow
  - pyflakes >= 2.4.0
  - pytest
  - requests
  - scikit-learn
  - scipy >=1.4.1
  - seaborn
  - statsmodels
  - tqdm
  - pip
  - pip:
    - opencv-python
